# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataTables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_id', models.IntegerField()),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('post_date', models.DateField()),
                ('identification', models.CharField(max_length=50)),
            ],
        ),
    ]
